name = "hinoto"
version = "0.0.1"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.

description = ""
licences = ["MIT"]
repository = { type = "github", user = "Comamoca", repo = "hinoto" }
links = [
  { title = "Examples", href = "https://github.com/Comamoca/tree/main/example" },
  { title = "hinoto/cli", href = "https://github.com/Comamoca/hinoto_cli" }
]

[documentation]
pages = [
    { title = "Concepts", path = "concepts.html", source = "./docs/concepts.md" },
    { title = "QuickStart", path = "quickstart.html", source = "./docs/quickstart.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
conversation = ">= 2.0.2 and < 3.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
